[project]
name = "mcpdemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.6.0",
    "mysql>=0.0.3",
    "mysql-connector>=2.2.9",
    "selenium>=4.31.0",
    "tinydb>=4.8.2",
]
